//
//  ChatIconStyleKit.swift
//  PaintCode
//
//  Created by art rimbaud on 18/05/15.
//  Copyright (c) 2015 rimbaudcode. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//


import Cocoa

public class ChatIconStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfChatIcon: NSImage?
    }

    //// Drawing Methods

    public class func drawChatIcon() {

        //// Oval 2 Drawing
        var oval2Path = NSBezierPath()
        oval2Path.moveToPoint(NSMakePoint(105.65, 146.5))
        oval2Path.curveToPoint(NSMakePoint(55.59, 133.03), controlPoint1: NSMakePoint(87.51, 146.36), controlPoint2: NSMakePoint(69.43, 141.87))
        oval2Path.curveToPoint(NSMakePoint(35.44, 93.08), controlPoint1: NSMakePoint(38.57, 122.15), controlPoint2: NSMakePoint(31.85, 107.19))
        oval2Path.lineCapStyle = NSLineCapStyle.RoundLineCapStyle
        NSColor.grayColor().setStroke()
        oval2Path.lineWidth = 9
        oval2Path.stroke()


        //// Bezier 2 Drawing
        var bezier2Path = NSBezierPath()
        bezier2Path.moveToPoint(NSMakePoint(166.1, 141.72))
        bezier2Path.curveToPoint(NSMakePoint(166.1, 58.28), controlPoint1: NSMakePoint(199.3, 118.68), controlPoint2: NSMakePoint(199.3, 81.32))
        bezier2Path.curveToPoint(NSMakePoint(89.68, 42.09), controlPoint1: NSMakePoint(145.34, 43.87), controlPoint2: NSMakePoint(116.5, 38.47))
        bezier2Path.curveToPoint(NSMakePoint(43.5, 20.5), controlPoint1: NSMakePoint(71.56, 30.34), controlPoint2: NSMakePoint(43.5, 20.5))
        bezier2Path.curveToPoint(NSMakePoint(58.33, 51.14), controlPoint1: NSMakePoint(43.5, 20.5), controlPoint2: NSMakePoint(53.16, 36.89))
        bezier2Path.curveToPoint(NSMakePoint(45.9, 58.28), controlPoint1: NSMakePoint(53.95, 53.2), controlPoint2: NSMakePoint(49.78, 55.58))
        bezier2Path.curveToPoint(NSMakePoint(45.9, 141.72), controlPoint1: NSMakePoint(12.7, 81.32), controlPoint2: NSMakePoint(12.7, 118.68))
        bezier2Path.curveToPoint(NSMakePoint(166.1, 141.72), controlPoint1: NSMakePoint(79.09, 164.76), controlPoint2: NSMakePoint(132.91, 164.76))
        bezier2Path.closePath()
        NSColor.redColor().setStroke()
        bezier2Path.lineWidth = 9
        bezier2Path.stroke()
    }

    //// Generated Images

    public class var imageOfChatIcon: NSImage {
        if Cache.imageOfChatIcon != nil {
            return Cache.imageOfChatIcon!
        }

        Cache.imageOfChatIcon = NSImage(size: NSMakeSize(210, 190), flipped: false) { (NSRect) -> Bool in 
                ChatIconStyleKit.drawChatIcon()

            return true
        }

        return Cache.imageOfChatIcon!
    }

}
